//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIEmployee.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class practiceDatabaseEntities : DbContext
    {
        public practiceDatabaseEntities()
            : base("name=practiceDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_DEPARTMENT> TBL_DEPARTMENT { get; set; }
        public virtual DbSet<TBL_EMPLOYEE> TBL_EMPLOYEE { get; set; }
        public virtual DbSet<TBL_MONTH> TBL_MONTH { get; set; }
        public virtual DbSet<TBL_SALARY> TBL_SALARY { get; set; }
        public virtual DbSet<TBL_YEAR> TBL_YEAR { get; set; }
    
        public virtual ObjectResult<SP_DEPARTMENT_OPERATION_Result> SP_DEPARTMENT_OPERATION()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DEPARTMENT_OPERATION_Result>("SP_DEPARTMENT_OPERATION");
        }
    
        public virtual ObjectResult<SP_DEPTCRUD_Result> SP_DEPTCRUD(string aCTION, Nullable<int> iD, string nAME)
        {
            var aCTIONParameter = aCTION != null ?
                new ObjectParameter("ACTION", aCTION) :
                new ObjectParameter("ACTION", typeof(string));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DEPTCRUD_Result>("SP_DEPTCRUD", aCTIONParameter, iDParameter, nAMEParameter);
        }
    
        public virtual int SP_EMPLOYEECRUD(string aCTION, Nullable<int> iD, string fIRSTNAME, string lASTNAME, string eMPLOYEEID, string gENDER, string aDDRESS, string pHONENUMBER, string eMAILID, Nullable<System.DateTime> dATEOFBIRTH, Nullable<int> dEPARTMENTID, Nullable<System.DateTime> dATEOFJOINING, string pHOTO, ObjectParameter rETURN_VALUE)
        {
            var aCTIONParameter = aCTION != null ?
                new ObjectParameter("ACTION", aCTION) :
                new ObjectParameter("ACTION", typeof(string));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var fIRSTNAMEParameter = fIRSTNAME != null ?
                new ObjectParameter("FIRSTNAME", fIRSTNAME) :
                new ObjectParameter("FIRSTNAME", typeof(string));
    
            var lASTNAMEParameter = lASTNAME != null ?
                new ObjectParameter("LASTNAME", lASTNAME) :
                new ObjectParameter("LASTNAME", typeof(string));
    
            var eMPLOYEEIDParameter = eMPLOYEEID != null ?
                new ObjectParameter("EMPLOYEEID", eMPLOYEEID) :
                new ObjectParameter("EMPLOYEEID", typeof(string));
    
            var gENDERParameter = gENDER != null ?
                new ObjectParameter("GENDER", gENDER) :
                new ObjectParameter("GENDER", typeof(string));
    
            var aDDRESSParameter = aDDRESS != null ?
                new ObjectParameter("ADDRESS", aDDRESS) :
                new ObjectParameter("ADDRESS", typeof(string));
    
            var pHONENUMBERParameter = pHONENUMBER != null ?
                new ObjectParameter("PHONENUMBER", pHONENUMBER) :
                new ObjectParameter("PHONENUMBER", typeof(string));
    
            var eMAILIDParameter = eMAILID != null ?
                new ObjectParameter("EMAILID", eMAILID) :
                new ObjectParameter("EMAILID", typeof(string));
    
            var dATEOFBIRTHParameter = dATEOFBIRTH.HasValue ?
                new ObjectParameter("DATEOFBIRTH", dATEOFBIRTH) :
                new ObjectParameter("DATEOFBIRTH", typeof(System.DateTime));
    
            var dEPARTMENTIDParameter = dEPARTMENTID.HasValue ?
                new ObjectParameter("DEPARTMENTID", dEPARTMENTID) :
                new ObjectParameter("DEPARTMENTID", typeof(int));
    
            var dATEOFJOININGParameter = dATEOFJOINING.HasValue ?
                new ObjectParameter("DATEOFJOINING", dATEOFJOINING) :
                new ObjectParameter("DATEOFJOINING", typeof(System.DateTime));
    
            var pHOTOParameter = pHOTO != null ?
                new ObjectParameter("PHOTO", pHOTO) :
                new ObjectParameter("PHOTO", typeof(string));
            var temp = ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EMPLOYEECRUD", aCTIONParameter, iDParameter, fIRSTNAMEParameter, lASTNAMEParameter, eMPLOYEEIDParameter, gENDERParameter, aDDRESSParameter, pHONENUMBERParameter, eMAILIDParameter, dATEOFBIRTHParameter, dEPARTMENTIDParameter, dATEOFJOININGParameter, pHOTOParameter, rETURN_VALUE);
            Console.WriteLine("i am printing"+temp);
            return temp;
        }
    
        public virtual ObjectResult<SP_FILTER_EMPLOYEE_WITH_BIRTH_Result> SP_FILTER_EMPLOYEE_WITH_BIRTH(Nullable<int> dEPARTMENTID)
        {
            var dEPARTMENTIDParameter = dEPARTMENTID.HasValue ?
                new ObjectParameter("DEPARTMENTID", dEPARTMENTID) :
                new ObjectParameter("DEPARTMENTID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_FILTER_EMPLOYEE_WITH_BIRTH_Result>("SP_FILTER_EMPLOYEE_WITH_BIRTH", dEPARTMENTIDParameter);
        }
    
        public virtual ObjectResult<SP_SALARY_DATABOUND_Result> SP_SALARY_DATABOUND(string aCTION)
        {
            var aCTIONParameter = aCTION != null ?
                new ObjectParameter("ACTION", aCTION) :
                new ObjectParameter("ACTION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SALARY_DATABOUND_Result>("SP_SALARY_DATABOUND", aCTIONParameter);
        }
    
        public virtual int SP_SALARYCRUD(string aCTION, Nullable<int> eMPID, Nullable<int> bASICPAY, Nullable<int> tA, Nullable<int> dA, Nullable<int> hRA, Nullable<int> mONTH, Nullable<int> yEAR, Nullable<int> iD, Nullable<int> dEPTID, ObjectParameter rETURN_VALUE)
        {
            var aCTIONParameter = aCTION != null ?
                new ObjectParameter("ACTION", aCTION) :
                new ObjectParameter("ACTION", typeof(string));
    
            var eMPIDParameter = eMPID.HasValue ?
                new ObjectParameter("EMPID", eMPID) :
                new ObjectParameter("EMPID", typeof(int));
    
            var bASICPAYParameter = bASICPAY.HasValue ?
                new ObjectParameter("BASICPAY", bASICPAY) :
                new ObjectParameter("BASICPAY", typeof(int));
    
            var tAParameter = tA.HasValue ?
                new ObjectParameter("TA", tA) :
                new ObjectParameter("TA", typeof(int));
    
            var dAParameter = dA.HasValue ?
                new ObjectParameter("DA", dA) :
                new ObjectParameter("DA", typeof(int));
    
            var hRAParameter = hRA.HasValue ?
                new ObjectParameter("HRA", hRA) :
                new ObjectParameter("HRA", typeof(int));
    
            var mONTHParameter = mONTH.HasValue ?
                new ObjectParameter("MONTH", mONTH) :
                new ObjectParameter("MONTH", typeof(int));
    
            var yEARParameter = yEAR.HasValue ?
                new ObjectParameter("YEAR", yEAR) :
                new ObjectParameter("YEAR", typeof(int));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var dEPTIDParameter = dEPTID.HasValue ?
                new ObjectParameter("DEPTID", dEPTID) :
                new ObjectParameter("DEPTID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SALARYCRUD", aCTIONParameter, eMPIDParameter, bASICPAYParameter, tAParameter, dAParameter, hRAParameter, mONTHParameter, yEARParameter, iDParameter, dEPTIDParameter, rETURN_VALUE);
        }
    
        public virtual ObjectResult<SP_SELECT_EMPLOYEE_Result> SP_SELECT_EMPLOYEE(Nullable<int> dEPT_ID, string yEAR, Nullable<int> eMP_ID, string nAME)
        {
            var dEPT_IDParameter = dEPT_ID.HasValue ?
                new ObjectParameter("DEPT_ID", dEPT_ID) :
                new ObjectParameter("DEPT_ID", typeof(int));
    
            var yEARParameter = yEAR != null ?
                new ObjectParameter("YEAR", yEAR) :
                new ObjectParameter("YEAR", typeof(string));
    
            var eMP_IDParameter = eMP_ID.HasValue ?
                new ObjectParameter("EMP_ID", eMP_ID) :
                new ObjectParameter("EMP_ID", typeof(int));
    
            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SELECT_EMPLOYEE_Result>("SP_SELECT_EMPLOYEE", dEPT_IDParameter, yEARParameter, eMP_IDParameter, nAMEParameter);
        }
    
        public virtual ObjectResult<SP_SELECT_EMPLOYEE_WITH_DEPARTMENT_Result> SP_SELECT_EMPLOYEE_WITH_DEPARTMENT(Nullable<int> dEPARTMENTID)
        {
            var dEPARTMENTIDParameter = dEPARTMENTID.HasValue ?
                new ObjectParameter("DEPARTMENTID", dEPARTMENTID) :
                new ObjectParameter("DEPARTMENTID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SELECT_EMPLOYEE_WITH_DEPARTMENT_Result>("SP_SELECT_EMPLOYEE_WITH_DEPARTMENT", dEPARTMENTIDParameter);
        }
    
        public virtual ObjectResult<SP_SELECT_SALARY_Result> SP_SELECT_SALARY(Nullable<int> dEPT_ID, Nullable<int> yEAR, Nullable<int> mONTH, Nullable<int> eMPID, Nullable<int> iD)
        {
            var dEPT_IDParameter = dEPT_ID.HasValue ?
                new ObjectParameter("DEPT_ID", dEPT_ID) :
                new ObjectParameter("DEPT_ID", typeof(int));
    
            var yEARParameter = yEAR.HasValue ?
                new ObjectParameter("YEAR", yEAR) :
                new ObjectParameter("YEAR", typeof(int));
    
            var mONTHParameter = mONTH.HasValue ?
                new ObjectParameter("MONTH", mONTH) :
                new ObjectParameter("MONTH", typeof(int));
    
            var eMPIDParameter = eMPID.HasValue ?
                new ObjectParameter("EMPID", eMPID) :
                new ObjectParameter("EMPID", typeof(int));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SELECT_SALARY_Result>("SP_SELECT_SALARY", dEPT_IDParameter, yEARParameter, mONTHParameter, eMPIDParameter, iDParameter);
        }
    
        public virtual ObjectResult<TBL_EMPLOYEE> SelectEmployee(Nullable<int> dEPT_ID, string yEAR, Nullable<int> eMP_ID, string nAME)
        {
            var dEPT_IDParameter = dEPT_ID.HasValue ?
                new ObjectParameter("DEPT_ID", dEPT_ID) :
                new ObjectParameter("DEPT_ID", typeof(int));
    
            var yEARParameter = yEAR != null ?
                new ObjectParameter("YEAR", yEAR) :
                new ObjectParameter("YEAR", typeof(string));
    
            var eMP_IDParameter = eMP_ID.HasValue ?
                new ObjectParameter("EMP_ID", eMP_ID) :
                new ObjectParameter("EMP_ID", typeof(int));
    
            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TBL_EMPLOYEE>("SelectEmployee", dEPT_IDParameter, yEARParameter, eMP_IDParameter, nAMEParameter);
        }
    
        public virtual ObjectResult<TBL_EMPLOYEE> SelectEmployee(Nullable<int> dEPT_ID, string yEAR, Nullable<int> eMP_ID, string nAME, MergeOption mergeOption)
        {
            var dEPT_IDParameter = dEPT_ID.HasValue ?
                new ObjectParameter("DEPT_ID", dEPT_ID) :
                new ObjectParameter("DEPT_ID", typeof(int));
    
            var yEARParameter = yEAR != null ?
                new ObjectParameter("YEAR", yEAR) :
                new ObjectParameter("YEAR", typeof(string));
    
            var eMP_IDParameter = eMP_ID.HasValue ?
                new ObjectParameter("EMP_ID", eMP_ID) :
                new ObjectParameter("EMP_ID", typeof(int));
    
            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TBL_EMPLOYEE>("SelectEmployee", mergeOption, dEPT_IDParameter, yEARParameter, eMP_IDParameter, nAMEParameter);
        }
    }
}
