//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIEmployee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EMPLOYEE
    {
        public int ID { get; set; }
        public string EMP_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string GENDER { get; set; }
        public string EMP_ADDRESS { get; set; }
        public string PHONE_NO { get; set; }
        public string EMAIL_ID { get; set; }
        public Nullable<System.DateTime> DATEOFBIRTH { get; set; }
        public Nullable<int> DEPT_ID { get; set; }
        public Nullable<System.DateTime> DATEOFJOINING { get; set; }
        public string PHOTO { get; set; }
        public Nullable<int> EMP_STATUS { get; set; }
    }
}
