//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIEmployee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SALARY
    {
        public int ID { get; set; }
        public int EMP_ID { get; set; }
        public Nullable<int> BASIC_PAY { get; set; }
        public Nullable<int> TA { get; set; }
        public Nullable<int> DA { get; set; }
        public Nullable<int> HRA { get; set; }
        public Nullable<int> MONTH { get; set; }
        public Nullable<int> YEAR { get; set; }
    }
}
